- .github/workflows/junction-python-ci.yml
- Cargo.lock
- crates/junction-api/src/error.rs
- crates/junction-api/src/kube/backend.rs
- crates/junction-api/src/kube/http.rs
- junction-python/Cargo.toml
- junction-python/junction/__init__.py
- junction-python/junction/requests.py
- junction-python/junction/urllib3.py
- junction-python/src/lib.rs
This PR adds some basic public functions for dumping backends and routes as Kubernetes objects. The python versions dump straight to YAML, while the Rust versions return structured data.
Routes get dumped as straight HTTPRoute objects:
```python
for route in some_cool_routes:
print("---")
print(junction.dump_kube_route(route))
```
```bash
$ python dump-routes.py > routes.yaml
$ kubectl apply -f routes.yaml
```
While Backends get dumped as partial Service objects that can be applied with `kubectl patch`. 
```python
with open("backend-patch.yaml", mode='w') as f:
f.write(junction.dump_backend(backend))
```
```bash
$ python dump-backend.py
$ kubectl patch --patch-file backend-patch.yaml svc/cool-service
```
Once this is done, I can get an `ezbake` released that reads HTTPRoutes and Services …
> Change k8s Service representation, add functions for dumping YAML

- crates/junction-api/src/backend.rs
- crates/junction-api/src/http.rs
- crates/junction-api/src/kube/http.rs
- crates/junction-api/src/lib.rs
- crates/junction-api/src/shared.rs
Cleaned up some modules that didn't need to be public, added some very basic rustdoc everywhere, and fixed a bunch of broken links.
> Make empty modules private, and add some basic module doc everywhere

- crates/junction-api-gen/src/main.rs
- crates/junction-api/src/backend.rs
- crates/junction-api/src/http.rs
- crates/junction-api/src/kube/backend.rs
- crates/junction-api/src/kube/http.rs
- crates/junction-api/src/lib.rs
- crates/junction-api/src/shared.rs
- crates/junction-api/src/xds/backend.rs
- crates/junction-api/src/xds/http.rs
- crates/junction-api/src/xds/shared.rs
- crates/junction-core/examples/get-endpoints.rs
- crates/junction-core/src/client.rs
- crates/junction-core/src/error.rs
- crates/junction-core/src/lib.rs
- crates/junction-core/src/load_balancer.rs
- crates/junction-core/src/xds/cache.rs
- crates/junction-core/src/xds/resources.rs
- junction-python/junction/config.py
- junction-python/src/lib.rs
More public API reshaping. After this change, `junction_api::shared` is no more. The types we want folks to use are all exposed at the top-level of the crate, or in `http` or `backend`.
There should be no actual change in functionality here.
> Move public types to top level, hide the shared module

- Cargo.lock
- Cargo.toml
- crates/junction-api/Cargo.toml
- crates/junction-api/src/backend.rs
- crates/junction-api/src/error.rs
- crates/junction-api/src/http.rs
- crates/junction-api/src/kube/backend.rs
- crates/junction-api/src/kube/http.rs
- crates/junction-api/src/lib.rs
- crates/junction-api/src/shared.rs
- crates/junction-api/src/xds/backend.rs
- crates/junction-api/src/xds/http.rs
- crates/junction-core/examples/get-endpoints.rs
- crates/junction-core/src/client.rs
- crates/junction-core/src/error.rs
- crates/junction-core/src/lib.rs
- crates/junction-core/src/url.rs
- crates/junction-core/src/xds.rs
- crates/junction-core/src/xds/cache.rs
- crates/junction-core/src/xds/resources.rs
- crates/junction-core/src/xds/test.rs
- junction-python/junction/config.py
- junction-python/samples/routing-and-load-balancing/client.py
- junction-python/src/lib.rs
- junction-python/tests/test_routes.py
Huge update that uses `Target::name` as the canonical xDS name we request, everywhere. This requires an update to `ezbake` to be functional. There's some chicken-and-egg dependence here, since to update `ezbake` we need this code to land. I'm going to try to have `ezbake` depend on this branch, build a new container, and then run smoke tests here.
All of our xDS now uses `Target::name` as it's Listener/Cluster/etc. name. While there's no xDS level requirement for a strict naming convention, we need to be able to encode a Target into a xDS name so we can decode exactly what kind of Target we're getting when we convert a `RouteConfiguration` to a `Route` or a `Cluster` to a `Backend`.
Getting serious about `Target::name` means taking ports seriously, and rationalizing multiple ports per …
> Use Target name as xDS resource name

- crates/junction-core/src/client.rs
- crates/junction-core/src/load_balancer.rs
Load balancing still had a parameter for passing Route session affinity to merge with LB affinity parameters. Get rid of it for now, we can bring it back if necessary.
> Clean up an old reference to Route affinity

- .github/workflows/docs-rust.yml
- Cargo.lock
- Cargo.toml
- crates/junction-api-gen/Cargo.toml
- crates/junction-api/Cargo.toml
- crates/junction-api/src/kube.rs
- crates/junction-api/src/kube/http.rs
- crates/junction-api/src/lib.rs
- junction-python/Cargo.toml
- xtask/src/main.rs
This is two changes in one PR, both of which make it easier to deal with `kube` deps.
`junction_api::kube` now re-exports `k8s-openapi` and `gateway-api` so anyone who depends on this crate can use types that they know are from the same dependency version. This doesn't appear to require exporting `kube` types anywhere, but I'll keep an eye out.
I went with a straight re-export of the crate instead of re-exporting its top-level contents and the `junction_api::kube` module has links out as appropriate. We could do the alternative [like rustls does for pki-types](https://docs.rs/rustls/0.23.15/src/rustls/lib.rs.html#634-637) but I'm not sure what the tradeoffs are here.
I upgraded `gateway-api` to 0.14 which has v1.2.0 Gateway types and a bunch of build fixes for . I didn't actually add …
> Re-export kube types and upgrade the Gateway API

- crates/junction-core/src/client.rs
- junction-python/samples/routing-and-load-balancing/client.py
We've been assuming that Routes contain enough information to fully resolve an xDS tree. If we allow a `Route`'s backend targets to omit the port, but require a port on a `Backend`'s target, that stops being the case - we end up subscribing to portless `Backend`s and failing to route.
To make this more concrete:
```python
default_target: junction.config.Target = {
"name": "jct-http-server",
"namespace": "default",
}
default_routes: List[junction.config.Route] = [
{
"target": default_target,
"rules": [
{
"backends": [
default_target,
]
},
],
}
]
```
This `Route` will use the port in the URL to resolve to the actual port for `default_target`, but when creating a new Client, we'll attempt to subscribe to xDS for `jct-http-server.default` with no port, which we're starting to say will never …
> junction-core: Add Cluster subscriptions after resolving routes

- Cargo.lock
- crates/junction-api-gen/src/main.rs
- crates/junction-api/src/backend.rs
- crates/junction-api/src/http.rs
- crates/junction-api/src/kube/backend.rs
- crates/junction-api/src/kube/http.rs
- crates/junction-api/src/lib.rs
- crates/junction-api/src/xds/backend.rs
- crates/junction-api/src/xds/http.rs
- crates/junction-core/Cargo.toml
- crates/junction-core/examples/get-endpoints.rs
- crates/junction-core/src/client.rs
- crates/junction-core/src/endpoints.rs
- crates/junction-core/src/error.rs
- crates/junction-core/src/lib.rs
- crates/junction-core/src/load_balancer.rs
- crates/junction-core/src/xds.rs
- crates/junction-core/src/xds/cache.rs
- crates/junction-core/src/xds/resources.rs
- junction-python/junction/config.py
- junction-python/samples/routing-and-load-balancing/client.py
- junction-python/src/lib.rs
- junction-python/tests/test_routes.py
First pass at requiring ports for Backends. This involved no longer having `Target` everywhere, and specifying `Route` and `Backend` targets differently. There's more work here to make here to start allowing passthrough-ports by making the `backends` section of a RouteRule optional - in that case we'll use the top-level `Route` info and fill in the port based on the request URL. That may come in another commit or in another PR, but is what's required to undo the change from https://github.com/junction-labs/ezbake/pull/35.
`Target` is no longer the greatest name and needs some work to clean up - I'm tempted to rename `RouteTarget` to something like `RouteName` and `BackendTarget` to something like `BackendId`.
> Require ports for Backends

- crates/junction-api-gen/src/python.rs
- crates/junction-api/src/http.rs
- crates/junction-api/src/kube/http.rs
- crates/junction-api/src/xds/http.rs
- crates/junction-core/examples/get-endpoints.rs
- crates/junction-core/src/client.rs
- crates/junction-typeinfo/src/lib.rs
- junction-python/junction/config.py
Adds an unstructured tags field to `Route` so we can smuggle metadata. xDS supports this with an explicit `metadata` field on RouteConfigurations and Listeners, and the Kube APIs support this through `annotations`.
The only downstream impact of that change is:
- We had to add `typing.Dict` support to junction-api-gen
- The conversions to/from the Gateway API structs now require full objects instead of just the `spec` so that we can look at annotations.
> Add an unstructured `tags` field to Route

- crates/junction-api/src/http.rs
- crates/junction-api/src/xds/backend.rs
- crates/junction-core/src/client.rs
Stop guessing at when a Route was auto-generated based on structure and start using the explicit junctionlabs.io/generated-by tag on Routes.
> Use the generated-by tag to pick between default and xds routes

- .github/workflows/smoke-test.yml
- README.md
- README_ALPHA_TESTERS.md
- junction-python/samples/routing-and-load-balancing/Dockerfile-client
Use the maturin action (see #69 ) to build a wheel and test that in our smoke tests, instead of copying the wheel into our containers manually. This gives us a slightly more realistic test of what folks will install/run and means we can maybe re-use this in the `python-ci` action as well. That probably involves combining workflows in a bit of an unpleasant way or dealing with cross-workflow dependencies so I'm holding off on it for now.
This also changes the client Docker example to require a `junction_wheel` build arg. The only place that seems to get used is in this test.
> Use a built wheel in smoke tests

- crates/junction-api/src/http.rs
- crates/junction-api/src/kube/http.rs
- crates/junction-api/src/xds/http.rs
- crates/junction-core/src/client.rs
- crates/junction-core/src/error.rs
- crates/junction-core/src/url.rs
- junction-python/junction/config.py
- junction-python/src/lib.rs
- junction-python/tests/test_routes.py
allows specifying a route with either missing backends, or missing match rules all together, that pass through traffic to a Route's vhost. this is a convenient shorthand for allowing routes that just configure timeouts and retries without getting into any route matching features. For example, this is now valid:
```python
route: config.Route = {
"vhost": nginx,
"rules": [
{
"retry": {
"attempts": 3,
}
},
],
}
```
There's a fair bit of line noise in this PR, but the meat of the interesting changes are in `junction-core` in `client.rs`. 
To get this to work with xDS, I'm shoving the route's `vhost` into the RouteAction cluster specifier instead of a `BackendId`. The client tries to parse a `BackendId` with a port, and if it can't find one, tries to parse the cluster specfier as a VirtualHost …
> Allow omitting backends and route rules to pass-through ports

- README.md
- crates/junction-api/src/http.rs
- crates/junction-api/src/lib.rs
- junction-python/junction/config.py
Rewrote the top-level rustdoc to be a better overview. Modified some field comments to keep Rustdoc from getting copied into Python as well.
This isn't "done", but feels like a step in the right direction.
> Rewrite top level rustdoc the crate::http rustdoc

- crates/junction-core/src/xds/csds.rs
I found a bug in CSDS status reporting while looking into an ezbake bug. No matter what the status of a resource is, we'd report it as NACKed.
> Fix CSDS resource status

- crates/junction-api/src/xds/backend.rs
- crates/junction-core/examples/dns-backend.rs
- crates/junction-core/src/client.rs
- crates/junction-core/src/dns.rs
- crates/junction-core/src/endpoints.rs
- crates/junction-core/src/lib.rs
- crates/junction-core/src/load_balancer.rs
- crates/junction-core/src/xds.rs
- crates/junction-core/src/xds/cache.rs
- crates/junction-core/src/xds/resources.rs
- crates/junction-core/src/xds/test.rs
This was originally going to be a branch for just some prep-work, but one thing kind of led to another and the changes are all kind of in one large commit. There's a few small prep commits that are potentially worth reviewing on their own, and then a big one for DNS.
Originally we hadn't been strict about how Backends became clusters, but now that we're taking DNS seriously it seemed like the right time to do so. We now follow the gRPC representation, where DNS clusters use a single in-line ClusterLoadAssignment to represent the DNS name they target and always use an EDS ClusterLoadAssignment for EDS clusters (any other kind of Junction Backend). 
Apparently we've been parsing IP addresses as DNS names this whole time. It hasn't yet mattered - we have endpoint support for hostnames, since …
> Resolve DNS targets

- crates/junction-api/src/lib.rs
- crates/junction-api/src/xds/backend.rs
- crates/junction-api/src/xds/http.rs
- crates/junction-core/src/xds/cache.rs
- crates/junction-core/src/xds/resources.rs
- crates/junction-core/src/xds/test.rs
LB Config routes have been polluting the actual set of Routes we generate. they haven't affected matches yet, for whatever reason, but I think that's us getting lucky with the order of operations.
This CR makes it explicit that an xDS listener can either be LB config or a Junction Route, and that a RouteConfig shouldn't be both. It also inspired some long-overdue cleanup: LB config routes are now creatively called `lb_config` wherever they show up, and not called `passthrough` routes anymore, to distinguish them from actual no backend pass-through routes.
> Fix some names, disambiguate LB config from actual routes

- crates/junction-api/src/shared.rs
- crates/junction-core/examples/dns-backend.rs
- crates/junction-core/examples/get-endpoints.rs
- crates/junction-core/src/client.rs
- crates/junction-core/src/dns.rs
- crates/junction-core/src/endpoints.rs
- crates/junction-core/src/error.rs
- crates/junction-core/src/lib.rs
- crates/junction-core/src/rand.rs
- crates/junction-core/src/xds.rs
- crates/junction-core/src/xds/cache.rs
- junction-python/junction/__init__.py
- junction-python/junction/requests.py
- junction-python/junction/urllib3.py
- junction-python/samples/routing-and-load-balancing/client.py
- junction-python/src/lib.rs
All of our `resolve_*` methods now block until data is available in cache until there's data available. This is still a real rough cut at that behavior, and we have some client configuring/tuning to make available, but it involves significant enough changes that I want to land it now and iterate instead of continuing to block this.
The big surface-level change is that everything we're doing is async now. Route resolution is async because it's allowed to yield while waiting for results in the cache, which touches all of the cache internals. That touches everything upstream and downstream - including the DNS resolver. This notably *doesn't* touch our unit-test style methods, which is great - we can use static config and [now_or_never](https://docs.rs/futures/latest/futures/future/trait.Futur …
> junction-core: make resolution async, make defaults easier to reason about

- Cargo.lock
- crates/junction-api/Cargo.toml
- crates/junction-core/Cargo.toml
- junction-python/Cargo.toml
Bump junction-python and junction-core to pick up the newly changed Route definition.
> Update to 0.2.0

- crates/junction-api-gen/src/main.rs
- crates/junction-api/src/backend.rs
- crates/junction-api/src/http.rs
- crates/junction-api/src/kube/backend.rs
- crates/junction-api/src/xds/backend.rs
- crates/junction-core/src/load_balancer.rs
- junction-python/junction/config.py
Add a QueryParam hash policy to RingHash that takes query parameters as inputs. the hash policy works exactly as the Header hash policy, except on HTTP query parameters.
```
(.venv) [21:01:08] benl@booger ~/s/j/junction-client (benl/query-param-ringhash *) $ python example.py
load balancer
{'type': 'RingHash', 'hash_params': [{'type': 'QueryParam', 'name': 'q'}]}
results:
{'q': 'hello'} target:jct-http-server,server_id:26
{'q': 'hello'} target:jct-http-server,server_id:26
{'q': 'hello'} target:jct-http-server,server_id:26
{'q': 'goodbye'} target:jct-http-server,server_id:20
{'q': 'goodbye'} target:jct-http-server,server_id:20
{'q': 'goodbye'} target:jct-http-server,server_id:20
```
Also removes an unused SessionAffinity struct that would have had to update.
> junction-api: Add a QueryParam hash policy to RingHash load balancing.

- crates/junction-api/src/http.rs
- crates/junction-api/src/kube/http.rs
- crates/junction-api/src/xds/http.rs
Add optional names to RouteRules so we can start to use them for debugging matches when producing request traces. This doesn't do anything yet, but as we go make request traces a thing it will help readability.
> Add an optional, human-readable name to RouteRules

- crates/junction-core/examples/dns-backend.rs
- crates/junction-core/examples/get-endpoints.rs
- crates/junction-core/src/client.rs
- crates/junction-core/src/dns.rs
- crates/junction-core/src/endpoints.rs
- crates/junction-core/src/hash.rs
- crates/junction-core/src/lib.rs
- crates/junction-core/src/load_balancer.rs
- crates/junction-core/src/xds.rs
- crates/junction-core/src/xds/cache.rs
- crates/junction-core/src/xds/resources.rs
- junction-python/junction/__init__.py
- junction-python/junction/requests.py
- junction-python/junction/urllib3.py
- junction-python/src/lib.rs
- junction-python/tests/test_urllib3.py
This is prep-work for status reporting on requests (both failed and successful) and for re-resolving addresses on retries, but involved a bunch of refactoring I wanted to land before it went on too long.
It hasn't ever made sense to return a `Vec<Endpoint>` but it was always something we could work around for the moment. The time has come to stop working around it and think more deeply about what we're returning. This PR trims down the vec to a single struct we're returning with basic info about what to connect to.
We'll end up adding to this over time (we'll almost certainly include resolution info and a list of mirroring addresses) but this is the basic struct we need for now.
We've ben handing off retries entirely to urllib3 but had to stop to hit two goals: setting an overall timeout …
> Set up for status reporting and re-resolving hosts on retries

- crates/junction-api/src/http.rs
- crates/junction-api/src/kube/http.rs
- crates/junction-api/src/xds/http.rs
- crates/junction-core/examples/dns-backend.rs
- crates/junction-core/examples/get-endpoints.rs
- crates/junction-core/src/client.rs
- crates/junction-core/src/endpoints.rs
- crates/junction-core/src/error.rs
- crates/junction-core/src/lib.rs
- crates/junction-core/src/load_balancer.rs
- crates/junction-core/src/url.rs
- junction-python/junction/urllib3.py
- junction-python/src/lib.rs
`report_status` actually does something now - it's not tracking status though! We're now re-selecting endpoints from the load balancer if the request needs to be retried. Since Endpoints carry around the entire RetryPolicy and the history of addresses tried (not unique addresses!), each Endpoint contains enough information to decide whether or not a new address should be selected.
That change is fairly minor, but required a bunch of interface changes and hiding the internals of Endpoint from public callers so we can smuggle enough data through, but still be relatively sure callers aren't mucking with Endpoint internals too much in a way that would mess with retries. 
There are two big choices in this PR worth calling out:
1) Endpoint has an opinion about how retries are done and …
> junction-core: Select new endpoints on retries, add Traces

- crates/junction-core/src/client.rs
- crates/junction-core/src/lib.rs
- crates/junction-core/src/load_balancer.rs
- crates/junction-core/src/url.rs
- junction-python/src/lib.rs
- junction-python/src/runtime.rs
This is a grab bag of two small commits and one small but detailed one.
3195757 fixes up some documentation. Easy.
da9e837 adds a helper method to dump xDS errors to make it easy to quickly introspect a client. Easy.
2799ad5 adds ctrl-c handling, and makes sure we release the GIL while blocking on Futures from sync Python. This is a bit hairy, because the GIL is reentrant but Futures may run on other threads. The change hides the tokio runtime behind a `spawn` wrapper that prevents holding the GIL by requiring that Futures are `Send` and a `block_on` wrapper that releases the GIL while the runtime blocks the thread on the `Future`.
> junction-python: docs, dump_xds_errors, and ctrl-c handling

- Cargo.lock
- crates/junction-api/Cargo.toml
- crates/junction-api/src/http.rs
- crates/junction-api/src/kube/http.rs
- crates/junction-api/src/shared.rs
Add an ordering to RouteRule and RouteMatch that complies with the Gateway API's rules for match precedence. 
https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.HTTPRouteRule
Sorting ahead of time won't guarantee compliance with the Gateway API's tiebreaking rules. It's possible to have a scenario where a rule R1 has matches A and C, and a rule R2 has a match B that means A > B > C, but R1 > R2. If a request matches B and C, evaluating rules in-order won't comply with the Gateway API's tie-breaking rules.
This seems like an extreme corner case, and not something we can find tested in the gateway conformance tests at this point - the closest thing we can see in conformance is [this test](https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/tests/htt …
> junction-api: add an ordering to RouteRule and RouteMatch

- crates/junction-core/src/client.rs
- crates/junction-core/src/error.rs
- crates/junction-core/src/lib.rs
- crates/junction-core/src/xds.rs
- junction-python/src/lib.rs
Fixes the occasional panic we had by actually making subscribing to a hostname/backend async. Moves it into the client to simplify the interface as well.
This gets rid of `ResolveMode`, which we hadn't really been using. There's no convenient way to pass that through without making caches fully aware of it. This makes the client simpler, but also means that testing route resolution with a client's currently fetched set of routes takes an extra step. That seems like an ok tradeoff.
There's also a commit in here that rejiggers timeout handling so that we can see individual timeouts for fetching backends and requests. Callers can now also pass a deadline when calling `resolve_route` and `select_endpoint`.
> junction-core: fix overload, make timeouts better

- .github/workflows/release-node.yaml
- .github/workflows/release-python.yaml
- junction-node/package-lock.json
- junction-node/package.json
- junction-node/platforms/darwin-arm64/package.json
- junction-node/platforms/darwin-x64/package.json
- junction-node/platforms/linux-arm64-gnu/package.json
- junction-node/platforms/linux-x64-gnu/package.json
- junction-node/platforms/win32-x64-msvc/package.json
- junction-node/scripts/postinstall.js
- xtask/src/main.rs
Adds an action to deploy to NPM. In debugging, this already successfully released 0.2.2 to npm!
We're all-in on installing platform native packages as optional dependencies and checking for them in a `postinstall` hook. This is what Neon pushes us towards anyway and what `biome` and other packages in the ecosystem seem to be trending towards. Our post-install hook is heavily inspired by [biome's](https://github.com/biomejs/biome/blob/main/packages/%40biomejs/biome/scripts/postinstall.js).
To get things to compile for linux-arm64 (Neon's defaults) I ended up using `cross`. It gets installed only on that target and appears to be using a container to cross-compile correctly. This seems like it's what `maturin` is doing under the hood for us as well if you inspect the actions output from …
> Add an action to deploy to NPM

- xtask/src/main.rs
Run clippy on `xtask`. Mostly an excuse to see if the xtask version bump in #125 actually fixed the cfg warnings.
> xtask: run clippy

- docs/source/getting-started/node.md
- docs/source/getting-started/python.md
Quick doc updates. Makes the direct use sections come last and adds a Node direct use example.
> docs: add Node direct use, make direct use come last

- crates/junction-core/src/client.rs
For some reason, I wrote `sleep_until` so that it immediately returns with no deadline. It should wait forever instead. Oops!
> junction-core: don't immediately time out with no deadline

- .github/workflows/junction-ci.yml
- Cargo.lock
- Cargo.toml
- crates/junction-api/Cargo.toml
- crates/junction-api/src/lib.rs
- crates/junction-core/src/client.rs
- crates/junction-core/src/dns.rs
- crates/junction-core/src/url.rs
- xtask/Cargo.toml
Adds support for ndots lookups, based on whatever is configured in your local `/etc/resolv.conf`. In Kube, we can now do things like `junction.resolve_http("GET", "http://mysvc", {})` and expect them to work as it would with DNS.
On every `resolve_http` call, we now compute a list of URLs based on the number of dots in a hostname and then race a full Junction lookup for every name in the list. The client assumes that the search list is priority ordered, and uses the first successful response in the list.
If every lookup in the search path fails, we'll return the error for the first name (the name that actually got passed in to the call to `resolve_http`) back to the client. There's an opportunity to do more here and include the entire list of names in the error. I'm punting that to …
> junction-core: ndots support

- Cargo.lock
- Cargo.toml
- junction-node/Cargo.toml
- junction-python/Cargo.toml
Bumping a 0.3.0 release 0.3.0 for junction-core, Python, and Node to pick up incremental xDS support and API changes in Python.
> Release 0.3.0

- Cargo.lock
- junction-node/Cargo.toml
- junction-node/package-lock.json
- junction-node/package.json
- junction-node/platforms/darwin-arm64/package.json
- junction-node/platforms/darwin-x64/package.json
- junction-node/platforms/linux-arm64-gnu/package.json
- junction-node/platforms/linux-x64-gnu/package.json
- junction-node/platforms/win32-x64-msvc/package.json
- xtask/src/main.rs
I forgot to bump optional dependencies when releasing `junction-node` 0.3.1. Bumps them, and modifies the `cargo xtask node version` task so we can't forget again.
> Fix node deps, bump junction-node to 0.3.1

- .github/actions/node-reference-docs/action.yaml
- .github/actions/python-reference-docs/action.yaml
- .github/workflows/docs-reference.yml
- junction-node/package-lock.json
- junction-python/docs/source/_static/version_switcher.json
- junction-python/docs/source/conf.py
- xtask/src/main.rs
Makes the doc release workflow a little easier to reason about by putting Node and Python docs in their own composite actions. This means we can do all the actions if/else in YAML once and then let those actions be much simpler.
Changes the Python doc release action to save docs for every patch version, instead of overwriting on X.Y releases. We realized that the Sphinx version switcher is manually populated, and are just going to save docs for every release until we have a reason not to.
Similarly, we're now versioning our Node typedoc output.
> Tidy up the doc release workflow

- crates/junction-core/src/client.rs
- junction-python/src/lib.rs
With ndots, xDS dumps were getting quite noisy - tombstones are clogging up our results. Since we're not expiring them or putting TTLs or timestamps on client-side caches yet, there's only value here if you want to see not-found resources. Hide them behind a boolean flag.
```
>>> pprint([{k: x.get(k) for k in ['name', 'version']} for x in j.dump_xds(not_found=True) if 'Listener' in x['type_url']])
[
│   {'name': 'nginx-staging.default.svc.cluster.local.lb.jct:80', 'version': '2s576DjfTR7sSEDEpPEaALZYuGn'},
│   {'name': 'nginx.bopp-vector.ts.net:80', 'version': None},
│   {'name': 'nginx.default.svc.cluster.local.lb.jct:80', 'version': '2s576DjfTR7sSEDEpPEaALZYuGn'},
│   {'name': 'nginx.default.svc.cluster.local:80', 'version': '2s58H93ELhaUQbN01cS3tUQztVj'},
│   {'name': 'nginx:80', …
```
> junction-python: omit xds tombstones in dump_xds

- README.md
Hi all,
Just a trivial change here: the README has a slightly broken link:
```
$ curl -so /dev/null -w "%{http_code}\n" https://docs.junctionlabs.io/getting-started/index.md
404
$ curl -so /dev/null -w "%{http_code}\n" https://docs.junctionlabs.io/getting-started/
200
$
```
Cheers!
Nathan
> [docs]: fix up broken link to the "getting started" page in the README

- .github/workflows/junction-python-ci.yml
- crates/junction-api-gen/src/python.rs
- junction-python/junction/__init__.py
- junction-python/junction/config.py
- junction-python/junction/requests.py
- junction-python/junction/urllib3.py
- junction-python/samples/smoke-test/Dockerfile
- junction-python/samples/smoke-test/client.py
- junction-python/tests/test_routes.py
Adjusts our type-hints to be compatible with Python 3.9. This mostly means switching to `typing.Union` everywhere we can instead of `|`, with some extra `typing.Optional` thrown in, but we had to drop some double-quotes from f-strings in tests.
Also updates CI so that we run Python CI on our minimum supported version of Python as well as our minimum supported Rust.
> junction-python: support for Python 3.9

- crates/junction-api-gen/Cargo.toml
- crates/junction-api/Cargo.toml
- crates/junction-core/Cargo.toml
- crates/junction-typeinfo-derive/Cargo.toml
- crates/junction-typeinfo/Cargo.toml
- junction-node/Cargo.toml
- junction-python/Cargo.toml
- xtask/Cargo.toml
I didn't realize that Cargo `workspace.package` metadata isn't auto-inherited so all of our sub-crates aren't picking up the workspace `rust-version`.
Updates every crate to use the workspace's `rust-version` so we stop getting clippy lints that conflict with our MSRV.
> clippy: add rust-version to all crates

- crates/junction-core/examples/dns-backend.rs
- crates/junction-core/examples/get-endpoints.rs
- crates/junction-core/src/client.rs
- junction-node/src/lib.rs
- junction-python/src/lib.rs
We've started seeing Already Borrowed exceptions from Pyo3 when using the client with an ASGI web server in the demo. @ptravers pointed out that `junction-core` doesn't actually require mutable access to the client, so there's no cost to removing the &mut access here.
> junction-core: Stop using &mut receivers in junction-client

- junction-node/build.rs
- junction-node/src/lib.rs
- junction-node/ts/core.cts
- junction-node/ts/index.cts
- junction-python/build.rs
- junction-python/junction/__init__.py
- junction-python/src/lib.rs
While debugging #164 we had a hard time figuring out what version of `junction` we were actually importing. It would have been really useful to have a runtime build version to look at, so we exposed one.
Like with the rest of the versioning here, we're using the version in `Cargo.toml` as the canonical library version. In both Python and Node we're just exposing [CARGO_PKG_VERSION](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates) at runtime.
> Expose build versions at runtime in Python and Node

- Cargo.lock
- Cargo.toml
- crates/junction-api/src/xds/http.rs
- crates/junction-core/src/xds/csds.rs
Upgrades `xds-api` to 0.2.0 which brings in new versions of tonic and prost.
`tonic` doesn't re-export either prost or axum so for now we're stuck on whatever versions of those dependencies that we build `xds-api` with.
> junction-core: Upgrade xds-api

- Cargo.lock
- crates/junction-core/src/xds.rs
- crates/junction-core/src/xds/cache.rs
- junction-python/Cargo.toml
- junction-python/junction/__init__.py
- junction-python/samples/smoke-test/client.py
- junction-python/src/lib.rs
We managed to turn up an add-remove-add bug where the client cache was marking an xDS Cluster as not-found when removing it instead of just removing it from the cache. This was, unfortunately, fairly easy to turn up - speeding up ingest and changing route names in the smoke test (a6cb862) were enough to trigger it reliably.
The fix is trivial - on removing a resource from the cache, don't create a subscription node if one doesn't already exist. 
```diff
fn remove(&mut self, rtype: ResourceType, name: &str) {
-        if let Some(sub) = self.find_subcribed(rtype, name) {
+        if let Some(sub) = self.find(rtype, name) {
self.reset_refs(sub);
}
}
```
For resources that are not wildcards, this was a noop, but for Clusters this would both tombstone resource data and create a wildcard …
> junction-core: Fix an add-remove-add caching bug

- README.md
What does this PR do?
---
Fixes the links for the rust, node, and python getting started pages by removing the `.md` ending from each one.
> fix: getting started links

- .github/workflows/junction-ci.yml
- .github/workflows/smoke-test.yml
We're not running actions on dependabot upgrades. Let's try doing that.
> chore: run actions on dependency upgrades
